version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing AWS CLI and amazon-connect-copy tool"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
      - export PATH="/usr/local/bin:$PATH"
      - git clone https://github.com/Mainak-Summit/amazon-connect-copy
      - cp amazon-connect-copy/bin/* /usr/local/bin
      - chmod 755 -R /usr/local/bin/

      - echo "Assuming source role in Account A"
      - SOURCE_ROLE=$(aws sts assume-role --role-arn "$SOURCE_ROLE_ARN" --role-session-name sourceSession)
      - export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' <<< "$SOURCE_ROLE")
      - export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' <<< "$SOURCE_ROLE")
      - export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' <<< "$SOURCE_ROLE")

      - echo "Assuming target role in Account B"
      - TARGET_ROLE=$(aws sts assume-role --role-arn "$TARGET_ROLE_ARN" --role-session-name targetSession)
      - export TARGET_AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' <<< "$TARGET_ROLE")
      - export TARGET_AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' <<< "$TARGET_ROLE")
      - export TARGET_AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' <<< "$TARGET_ROLE")

      # Define profiles for amazon-connect-copy
      - >
        printf "[source]\nregion=$SOURCE_REGION\naws_access_key_id=$AWS_ACCESS_KEY_ID
        aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
        aws_session_token=$AWS_SESSION_TOKEN\n" > ~/.aws/credentials
      - >
        printf "[target]\nregion=$TARGET_REGION\naws_access_key_id=$TARGET_AWS_ACCESS_KEY_ID
        aws_secret_access_key=$TARGET_AWS_SECRET_ACCESS_KEY
        aws_session_token=$TARGET_AWS_SESSION_TOKEN\n" >> ~/.aws/credentials

  build:
    commands:
      - echo "Starting replication process..."

      # Conditionally export source instance
      - |
        echo "Exporting from source instance ($SOURCE_REGION)..."
        export AWS_DEFAULT_REGION="$SOURCE_REGION"
        if [ "$SCOPE" = "ALL" ]; then
          connect_save -p source "$SOURCE_INSTANCE"
        else
          connect_save -p source -c "$SCOPE" "$SOURCE_INSTANCE"
        fi

      # Conditionally export target instance
      - |
        echo "Exporting from target instance ($TARGET_REGION)..."
        export AWS_DEFAULT_REGION="$TARGET_REGION"
        if [ "$SCOPE" = "ALL" ]; then
          connect_save -p target "$TARGET_INSTANCE"
        else
          connect_save -p target -c "$SCOPE" "$TARGET_INSTANCE"
        fi

      # Generate a diff
      - connect_diff "$SOURCE_INSTANCE" "$TARGET_INSTANCE" diff

      # Final apply to target instance
      - echo "Applying changes to target instance..."
      - export AWS_DEFAULT_REGION="$TARGET_REGION"
      - connect_copy diff

      # Upload to S3
      - date=$(date '+%Y/%m/%d')
      - s3_path="${SOURCE_ENV}_TO_${TARGET_ENV}"
      - aws s3 cp . "s3://${S3_BUCKET}/${date}/${s3_path}/${CODEBUILD_BUILD_NUMBER}" --recursive